### ISSUE TITLE
Text show up as white even if background is white.

### ISSUE THREAD

**Issue by regebro** [scopatz/xo#11]
Forcing the background color is probably the easiest fix.

This is very low priority, as I'm unlikely to actually use exofrills. I may howver steal large parts code for use in an editor/IDE, because I *do* want more frills. :-)

**Comment by scopatz** [comment]
Hi @regebro - I think that this is because the default style is monokai, You should be able to change the default style in the rc file by doing something like:

```console
$ xo --rc-edit
```

And then adding a JSON snippet that looks like: `{"style": "autumn"}` or some other preferred style.

 > I may howver steal large parts code for use in an editor/IDE, because I do want more frills. :-)

Please do :).  I am considering adding *some* frills, for what it is worth.  I'm interested in what features you are thinking about...

**Comment by regebro** [comment]
Well, I want line numbering and auto-completion.

In the end I actually want a full-featured IDE, so I'm making a editing Widget, so I can have one per file. Extracting your code into a widget turned out to be difficult though, but I'll probably take bits of your code for the syntax highlighting.
